## Put comments here that give an overall description of what your
## functions do

## This function takes a matrix and returns a list with get, set, setinverse and getinverse
## Usage example:
## mat <- matrix(rnorm(1:6),nrow=3,ncol=3)
## matrixObj <- makeCacheMatrix(mat)
makeCacheMatrix <- function(x = matrix()) {
        i <- NULL
        set <- function(y) {
                x <<- y
                i <<- NULL
        }
        get <- function() x
        setinverse <- function(inverse) i <<- inverse
        getinverse <- function() i
        list(set = set, get = get,
             setinverse = setinverse,
             getinverse = getinverse)
}


## This function caches the matrix inverse generated by the solve() function
## Usage example:
## cacheMatrix <- cacheSolve(matrixObj)

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        i <- x$getinverse()
        if(!is.null(i)) {
                message("getting cached data")
                return(i)
        }
        data <- x$get()
        i <- solve(data, ...)
        x$setinverse(i)
        i
}
